# Generated by Django 4.2.21 on 2025-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivousuario',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
    ]
