# Generated by Django 4.2.21 on 2025-06-13 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos/')),
                ('institucion_afiliada', models.CharField(blank=True, max_length=200, null=True)),
                ('puntos_prestigio', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_destacada', models.BooleanField(default=False)),
                ('codigo_invitacion', models.CharField(blank=True, max_length=10, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('spam', 'Spam'), ('contenido_inapropiado', 'Contenido inapropiado'), ('acoso', 'Acoso'), ('otro', 'Otro')], max_length=80)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M6_Comunidades.comunidad')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('rol', models.CharField(choices=[('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=10)),
                ('institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('rol', models.CharField(choices=[('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=10)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M6_Comunidades.comunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'comunidad')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('es_importante', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='M6_Comunidades.comunidad')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='comunidad',
            name='miembros',
            field=models.ManyToManyField(related_name='comunidades', through='M6_Comunidades.MiembroComunidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('procesada', models.BooleanField(default=False)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M6_Comunidades.comunidad')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comunidad', 'invitado')},
            },
        ),
    ]
